apiVersion: v1
kind: Secret
metadata:
  name: vaultcorp-secrets
  namespace: blue-1
type: Opaque
stringData:
  SECRET_KEY: "new-secret-key"
  DB_PASSWORD: "new-db-password"
  WALLET_PRIVATE_KEY: "new-wallet-key"
